language: php
sudo: required
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable10
    - APP_NAME=files_antivirus
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y clamav
  - which php
  - more `which pecl`
  - which phpize
  - bash tests/.travis/before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP_NAME

script:
  # Test lint
  - cd apps/$APP_NAME
  - sh -c "if [ '$DB' = 'sqlite' ]; then ant test; fi"

  # Run phpunit tests
  - php tests/util/avirserver.php &
  - cd tests/unit
  - ../../../../lib/composer/bin/phpunit --configuration phpunit.xml

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - php: 7
      env: DB=mysql
    - php: 7
      env: DB=pgsql
    - php: 7
      env: DB=oracle
    - php: 7.1
      env: DB=mysql CORE_BRANCH=master
    - php: 7.2
      env: DB=mysql CORE_BRANCH=master
  allow_failures:
    - php: hhvm
  fast_finish: true
